spring:
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mychat?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #    url: jdbc:mysql://47.116.19.68:3306/tea?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      #      生产环境改为none  b4c76de512f74f129e00934846720334  fff8ce8e14cb426ca0bd8bfd7104bbc9
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    format-sql: true
  data:
    redis:
      repositories:
        enabled: false